name: ci

on:
  push:
  pull_request:
  # daily check at 01:00 AM
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: setup deno
        uses: denolib/setup-deno@v2

      - name: run deno test
        run: deno test -A
         
